### ISSUE TITLE
1.2 主页 => 轮播图

### ISSUE THREAD

**Issue by woq** [woq/vue-zhihu-daily#6]
解决方案 Element 
- Carousel 走马灯

**Comment by woq** [comment]
标题,副标题显示
包裹一下图片，把文本用绝对定位显示在图片上


这以前也是个困扰我的问题 这种图片加文字我以为是很常见的操作 能改改标签排列就解决的
以为有什么优雅办法
结果一看大家都是定位玩


子绝父相 给子级给个zindex

曾几何时 我觉得css也是有逻辑的 有策略的 有一些原则的 直到后来 发现根本没什么几把原则 反正只要能实现就行了 就算你拿屎糊一座房子 只要他看起来和泥巴糊的一样 那就可以
工作了之后就只会flex一把梭

**Comment by woq** [comment]
```css
.carouselImg {
  position: absolute;
  bottom: 8px;
  left: 16px;
}
```
